services:
  app:
    build:
      context: .
    container_name: api-buguer-app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${YOUR_USERNAME}
      - POSTGRES_PASSWORD=${YOUR_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_DOCKER_PORT}/${YOUR_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${YOUR_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${YOUR_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "${LOCAL_PORT}:${DOCKER_PORT}"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root1914"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${YOUR_USERNAME}
      - POSTGRES_PASSWORD=${YOUR_PASSWORD}
      - POSTGRES_DB=${YOUR_DB_NAME}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgadmin_data:
